# Generated by Django 5.2.1 on 2025-10-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-data_criacao"]},
        ),
    ]
